/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author MYPC
 */
public class rent_out extends javax.swing.JFrame {

    /**
     * Creates new form rent_out
     */
    public rent_out() {
        initComponents();
        
        //setting invoice number by getting data from the database 
        int max_of_data=0;
        ResultSet rs;
        try{
           String q="select max(invoice_no) from invoice;";
           rs=dbcon.getData(q);
           
           while(rs.next())
           {
               max_of_data=rs.getInt(1);
           }
          
           
           
           }
           catch(Exception e)
           {
           JOptionPane.showMessageDialog(null,"Exception occured");
           }
       
        int x=max_of_data;
        x++;
        jLabel12_invoice_no.setText(String.valueOf(x));
        
        
         //filling the nic combobox
        String q_nic="select nic from customer where availability='available' AND rented_gameid='null'; ";
        try{
        ResultSet rs1=dbcon.getData(q_nic);
        
        while(rs1.next())
        {
            jComboBox1_nic.addItem(rs1.getString("nic"));
        }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"Exception occured when filling combo box");
        }
        
        jComboBox1_nic.setSelectedIndex(-1);
        
        //filling the gamename combobox
        String q_game="select game_name from games where availability='available' AND current_qty>0 ; ";
        try{
        ResultSet rs2=dbcon.getData(q_game);
        
        while(rs2.next())
        {
            jComboBox2_game.addItem(rs2.getString("game_name"));
        }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"Exception occured when filling combo box");
        }
        
        jComboBox2_game.setSelectedIndex(-1);
        jLabel5_innitial_amount.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1_nic = new javax.swing.JComboBox<>();
        jComboBox2_game = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5_innitial_amount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_discount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8_final_amount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8_cusname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jXDatePicker1_renting_date = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2_due_date = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12_invoice_no = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Renting out Games");

        jLabel2.setText("Customer NIC : ");

        jLabel3.setText("Game Name : ");

        jComboBox1_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_nicActionPerformed(evt);
            }
        });

        jComboBox2_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_gameActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount  Rs  : ");

        jLabel5_innitial_amount.setText("jLabel5");

        jLabel6.setText("Enter Discount Rs  : ");

        jTextField1_discount.setText("0");

        jLabel7.setText("Amount after discount  Rs: ");

        jLabel8_final_amount.setText("jLabel8");

        jLabel5.setText("Customer Name: ");

        jLabel8_cusname.setText("jLabel8");

        jLabel9.setText("Renting Out Date: ");

        jLabel10.setText("Due Date: ");

        jButton1.setText("Rent Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Invoice Number : ");

        jLabel12_invoice_no.setText("jLabel12");

        jButton3.setText("Give Discount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8_final_amount))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1_nic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8_cusname, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(jLabel5_innitial_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2_game, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12_invoice_no, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jXDatePicker2_due_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(31, 31, 31)
                                    .addComponent(jXDatePicker1_renting_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12_invoice_no))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8_cusname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2_game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5_innitial_amount))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8_final_amount))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jXDatePicker1_renting_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jXDatePicker2_due_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_nicActionPerformed
       String nic= (String)jComboBox1_nic.getSelectedItem();
       String q="select name from customer where availability='available' AND nic='"+nic+"' AND rented_gameid='null'";
       try{
       ResultSet rs=dbcon.getData(q);
       String name1="";
       while(rs.next())
       {
           name1=rs.getString("name");
       }
       jLabel8_cusname.setText(name1);
       }catch(Exception e){    JOptionPane.showMessageDialog(null,"Exception occured when customer name label");     }
    }//GEN-LAST:event_jComboBox1_nicActionPerformed
       
    private void jComboBox2_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_gameActionPerformed
      //filling the fee label with relavant game rental fee 
       String game_name= (String)jComboBox2_game.getSelectedItem();
       String q="select rental_fee from games where availability='available' AND game_name='"+game_name+"' AND current_qty>0";
       String fee="";
       try{
       ResultSet rs=dbcon.getData(q);
       
       while(rs.next())
       {
           fee=rs.getString("rental_fee");
       }
       jLabel5_innitial_amount.setText(fee);
       jLabel8_final_amount.setText(fee);
       }catch(Exception e){    JOptionPane.showMessageDialog(null,"Exception occured when customer name label");     }    }//GEN-LAST:event_jComboBox2_gameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         menu m = new menu();
           this.dispose();
           m.setVisible(true);      }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //calculating the final fee after giving a discount
        double discount=Double.parseDouble(jTextField1_discount.getText());
        double rent=Double.parseDouble(jLabel5_innitial_amount.getText());
        double amount_after_discount=rent-discount;
        jLabel8_final_amount.setText(String.valueOf(amount_after_discount));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // getting the renting date from the datepicker and converting it to a YYYY-MM-dd format
        String game_id1 =null;
        int game_id=0;
        String renting_date=null;
        String due_date=null;
        try{
        Date date_picker_rent=jXDatePicker1_renting_date.getDate();
        SimpleDateFormat date_r=new SimpleDateFormat("YYYY-MM-dd");
        renting_date=date_r.format(date_picker_rent);
        
        // getting the renting date from the datepicker and converting it to a YYYY-MM-dd format
        Date date_picker_due=jXDatePicker2_due_date.getDate();
        SimpleDateFormat date_d=new SimpleDateFormat("YYYY-MM-dd");
         due_date=date_d.format(date_picker_due);
        
        //getting game id from the database 
        
        game_id1=(String)jComboBox2_game.getSelectedItem();
        System.out.println(game_id1);
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Error");  }
        try{
        ResultSet rs=dbcon.getData("SELECT game_id FROM games WHERE game_name='"+game_id1+"' ;");
        while(rs.next())
        {
            game_id=rs.getInt("game_id");
        }
        }catch(Exception e){ JOptionPane.showMessageDialog(null,"Exception occured when getting the game ID from the Database");  }
        
        //inserting details into the invoice table
        games1.rent_out_game(Integer.parseInt(jLabel12_invoice_no.getText()),renting_date,(String)jComboBox1_nic.getSelectedItem(),game_id,Double.parseDouble(jLabel5_innitial_amount.getText()),Double.parseDouble(jTextField1_discount.getText()),Double.parseDouble(jLabel8_final_amount.getText()), due_date);
        
         jComboBox2_game.setSelectedIndex(-1);
         jComboBox1_nic.setSelectedIndex(-1);
         jLabel5_innitial_amount.setText(null);
         jLabel8_cusname.setText(null);
         jLabel5_innitial_amount.setText(null);
         jLabel8_final_amount.setText(null);
         jXDatePicker1_renting_date.setDate(null);
         jXDatePicker2_due_date.setDate(null);
         jTextField1_discount.setText(null);
         
         //setting invoice number by getting data from the database 
        int max_of_data=0;
        ResultSet rs;
        try{
           String q="select max(invoice_no) from invoice;";
           rs=dbcon.getData(q);
           
           while(rs.next())
           {
               max_of_data=rs.getInt(1);
           }
          
           
           
           }
           catch(Exception e)
           {
           JOptionPane.showMessageDialog(null,"Exception occured");
           }
       
        int x=max_of_data;
        x++;
        jLabel12_invoice_no.setText(String.valueOf(x));
        
        jComboBox1_nic.removeAllItems();
        jComboBox2_game.removeAllItems();

        //filling the nic combobox
        String q_nic="select nic from customer where availability='available' AND rented_gameid='null'; ";
        try{
        ResultSet rs3=dbcon.getData(q_nic);
        
        while(rs3.next())
        {
            jComboBox1_nic.addItem(rs3.getString("nic"));
        }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"Exception occured when filling combo box");
        }
        
        jComboBox1_nic.setSelectedIndex(-1);
        
        //filling the gamename combobox
        String q_game="select game_name from games where availability='available' AND current_qty>0 ; ";
        try{
        ResultSet rs4=dbcon.getData(q_game);
        
        while(rs4.next())
        {
            jComboBox2_game.addItem(rs4.getString("game_name"));
        }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"Exception occured when filling combo box");
        }
        
        jComboBox2_game.setSelectedIndex(-1);
        jLabel5_innitial_amount.setText(null);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rent_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rent_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rent_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rent_out.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rent_out().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1_nic;
    private javax.swing.JComboBox<String> jComboBox2_game;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12_invoice_no;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_innitial_amount;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8_cusname;
    private javax.swing.JLabel jLabel8_final_amount;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1_discount;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1_renting_date;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2_due_date;
    // End of variables declaration//GEN-END:variables
}
